spring:
  profiles:
      active: h2
  batch:
    job:
      enabled: false
    initializer:
      enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate.format_sql: false
      hibernate.cglib.use_reflection_optimizer: true
    hibernate:
      ddl-auto: none