-- noinspection SqlDialectInspectionForFile
-- noinspection SqlNoDataSourceInspectionForFile
--------------------------------------------------------
-- Archivo creado  - miércoles-agosto-31-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence S_GPE_ABSENCES
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_ABSENCES  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_GOALS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_GOALS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_HISTORICAL_PROJECTS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_HISTORICAL_PROJECTS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_INCURRED
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_INCURRED  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_PROJECTS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_PROJECTS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_REPORTS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_REPORTS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_REQUIREMENTS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_REQUIREMENTS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_SERVERS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_SERVERS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_TASKS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_TASKS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 361 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_TASKS_COMMENT
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_TASKS_COMMENT  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_TIMESHEETS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_TIMESHEETS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_TODO
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_TODO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_USERS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_USERS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_GPE_VACATIONS
--------------------------------------------------------

   CREATE SEQUENCE  S_GPE_VACATIONS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_ABSENCES
--------------------------------------------------------

  CREATE TABLE T_GPE_M_ABSENCES 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"COMMENTARY" VARCHAR2(100 CHAR), 
	"END_DATE" TIMESTAMP (6), 
	"START_DATE" TIMESTAMP (6), 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_DOCUMENTS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_DOCUMENTS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"DEVELOPER_AVAILABILITY" NUMBER(1,0), 
	"NAME" VARCHAR2(50 CHAR), 
	"URL" VARCHAR2(255 CHAR), 
	"DOCUMENT_TYPE_ID" NUMBER(19,0), 
	"PROJECT_ID" NUMBER(19,0), 
	"REQUIREMENT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_GOALS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_GOALS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"ACHIEVED" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(200 CHAR), 
	"PRIORITY" NUMBER(10,0), 
	"TITLE" VARCHAR2(30 CHAR), 
	"REQUIREMENT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_INCURREDS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_INCURREDS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"COMMENTARY" VARCHAR2(200 CHAR), 
	"EXTRA" NUMBER(1,0), 
	"MINUTES" NUMBER(10,0), 
	"TASK_ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_PROJECTS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_PROJECTS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"ARCHIVED" NUMBER(1,0), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CVS_CODE" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"END_DATE" TIMESTAMP (6), 
	"LAST_EDITION_BY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(20 CHAR), 
	"PROJECT_CODE" VARCHAR2(30 CHAR), 
	"PROJECT_LOGO" VARCHAR2(255 CHAR), 
	"PROJECT_TITLE" VARCHAR2(3 CHAR), 
	"START_DATE" TIMESTAMP (6), 
	"PROJECT_LEADER" NUMBER(19,0), 
	"METHODOLOGY" NUMBER(19,0), 
	"PRODUCT_OWNER" NUMBER(19,0), 
	"SCRUM_MASTER" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_REPORTS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_REPORTS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"FILENAME" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"REPORT_STATUS" NUMBER(19,0), 
	"REPORT_TYPE" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_REQUIREMENTS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_REQUIREMENTS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"ARCHIVED" NUMBER(1,0), 
	"CVS_CODE" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(200 CHAR), 
	"END_DATE" TIMESTAMP (6), 
	"HOURS" NUMBER(19,0), 
	"NAME" VARCHAR2(50 CHAR), 
	"REQUIREMENT_CODE" VARCHAR2(30 CHAR), 
	"START_DATE" TIMESTAMP (6), 
	"CREATED_BY" NUMBER(19,0), 
	"LAST_EDITION_BY" NUMBER(19,0), 
	"PROJECT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_ROLES
--------------------------------------------------------

  CREATE TABLE T_GPE_M_ROLES 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_SERVERS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_SERVERS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"HOSTNAME" VARCHAR2(255 CHAR), 
	"IP" VARCHAR2(255 CHAR), 
	"PROJECT_ID" NUMBER(19,0), 
	"SERVER_TYPE" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_TASK_COMMENT
--------------------------------------------------------

  CREATE TABLE T_GPE_M_TASK_COMMENT 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"COMMENTARY" VARCHAR2(500 CHAR), 
	"TASK_ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_TASKS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_TASKS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"CODE" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(200 CHAR), 
	"END_DATE" TIMESTAMP (6), 
	"HOURS" FLOAT(126), 
	"MANAGEMENT" NUMBER(1,0), 
	"NAME" VARCHAR2(50 CHAR), 
	"START_DATE" TIMESTAMP (6), 
	"CREATED_BY" NUMBER(19,0), 
	"LAST_EDITION_BY" NUMBER(19,0), 
	"PARENT_ID" NUMBER(19,0), 
	"REQUIREMENT_ID" NUMBER(19,0), 
	"TASK_PRIORITY_ID" NUMBER(19,0), 
	"TASK_STATUS_ID" NUMBER(19,0), 
	"TASK_TYPE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_TIMESHEETS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_TIMESHEETS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"END_DATE" TIMESTAMP (6), 
	"FRIDAY_HOURS" NUMBER(10,0), 
	"MONDAY_HOURS" NUMBER(10,0), 
	"SATURDAY_HOURS" NUMBER(10,0), 
	"START_DATE" TIMESTAMP (6), 
	"SUNDAY_HOURS" NUMBER(10,0), 
	"THURSDAY_HOURS" NUMBER(10,0), 
	"TUESDAY_HOURS" NUMBER(10,0), 
	"WEDNESDAY_HOURS" NUMBER(10,0), 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_TODOS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_TODOS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"DONE" NUMBER(1,0), 
	"TASK" VARCHAR2(30 CHAR), 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_USERS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_USERS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"ATTEMPTS" NUMBER(10,0), 
	"BIRTHDAY" TIMESTAMP (6), 
	"CITY" VARCHAR2(20 CHAR), 
	"COUNTRY" VARCHAR2(20 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"EXPIRING_DATE" TIMESTAMP (6), 
	"IDENTIFIER" VARCHAR2(20 CHAR), 
	"IS_ENABLED" NUMBER(1,0), 
	"LAST_LOGIN" TIMESTAMP (6), 
	"LOCKED" NUMBER(1,0), 
	"NAME" VARCHAR2(20 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"PHONE" VARCHAR2(255 CHAR), 
	"PHOTO_URL" VARCHAR2(255 CHAR), 
	"SURNAME" VARCHAR2(50 CHAR), 
	"ROLE_ID" NUMBER(19,0), 
	"USER_POSITION" NUMBER(19,0), 
	"VACATION_DAYS" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_M_VACATIONS
--------------------------------------------------------

  CREATE TABLE T_GPE_M_VACATIONS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"APPROVED" NUMBER(1,0), 
	"END_DATE" TIMESTAMP (6), 
	"START_DATE" TIMESTAMP (6), 
	"YEAR" NUMBER(10,0), 
	"USER_ID" NUMBER(19,0), 
	"MANAGED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_DOCUMENT_TYPES
--------------------------------------------------------

  CREATE TABLE T_GPE_P_DOCUMENT_TYPES 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_METHODOLOGIES
--------------------------------------------------------

  CREATE TABLE T_GPE_P_METHODOLOGIES 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_PRIORITY
--------------------------------------------------------

  CREATE TABLE T_GPE_P_PRIORITY 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_PUBLIC_HOLIDAYS
--------------------------------------------------------

  CREATE TABLE T_GPE_P_PUBLIC_HOLIDAYS 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"DAY" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_REPORT_STATUS
--------------------------------------------------------

  CREATE TABLE T_GPE_P_REPORT_STATUS 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_REPORT_TYPE
--------------------------------------------------------

  CREATE TABLE T_GPE_P_REPORT_TYPE 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_SERVER_TYPE
--------------------------------------------------------

  CREATE TABLE T_GPE_P_SERVER_TYPE 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_TASK_STATUS
--------------------------------------------------------

  CREATE TABLE T_GPE_P_TASK_STATUS 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"COLOR" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_TASK_TYPE
--------------------------------------------------------

  CREATE TABLE T_GPE_P_TASK_TYPE 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_P_USER_CATEGORY
--------------------------------------------------------

  CREATE TABLE T_GPE_P_USER_CATEGORY 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_R_HISTORICAL_PROJECTS
--------------------------------------------------------

  CREATE TABLE T_GPE_R_HISTORICAL_PROJECTS 
   (	"ID" NUMBER(19,0), 
	"TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(19,0), 
	"END_DATE" TIMESTAMP (6), 
	"START_DATE" TIMESTAMP (6), 
	"PROJECT_ID" NUMBER(19,0), 
	"REQUIREMENT_ID" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_R_PROJECTS_MANAGED
--------------------------------------------------------

  CREATE TABLE T_GPE_R_PROJECTS_MANAGED 
   (	"ID_USER" NUMBER(19,0), 
	"ID_PROJECT" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_R_REQUIREMENTS_DEVELOPED
--------------------------------------------------------

  CREATE TABLE T_GPE_R_REQUIREMENTS_DEVELOPED 
   (	"ID_USER" NUMBER(19,0), 
	"ID_REQUIREMENT" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_R_TASKS_ASSIGNED
--------------------------------------------------------

  CREATE TABLE T_GPE_R_TASKS_ASSIGNED 
   (	"ID_USER" NUMBER(19,0), 
	"ID_TASK" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Table T_GPE_R_TASKS_DEPENDENCIES
--------------------------------------------------------

  CREATE TABLE T_GPE_R_TASKS_DEPENDENCIES 
   (	"TASK_ID" NUMBER(19,0), 
	"DEPENDENCY_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for View V_GPE_LEADER_DASHBOARD
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW V_GPE_LEADER_DASHBOARD ("ID", "LEADER", "PROJECTS", "REQUIREMENTS", "MANAGERS", "DEVELOPERS", "ACTIVE_TASKS", "BLOCKED_TASKS", "DELAYED_TASKS", "STOPPED_TASKS") AS 
  SELECT rownum id ,
    leader,
    projects,
    requirements,
    managers,
    developers,
    active_Tasks,
    blocked_Tasks,
    delayed_Tasks,
    stopped_Tasks
  FROM
    (WITH q1 AS
    (SELECT u.ID leader,
      COUNT(DISTINCT(p.id))       AS projects,
      COUNT(DISTINCT(r.id))       AS requirements,
      COUNT(DISTINCT(rd.ID_USER)) AS developers,
      COUNT(DISTINCT(pm.ID_USER)) AS managers
    FROM T_GPE_M_USERS u
    LEFT JOIN T_GPE_M_PROJECTS p
    ON u.ID = p.PROJECT_LEADER
    LEFT JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    LEFT JOIN T_GPE_R_REQUIREMENTS_DEVELOPED rd
    ON rd.ID_REQUIREMENT = r.ID
    LEFT JOIN T_GPE_R_PROJECTS_MANAGED pm
    ON pm.ID_PROJECT = p.ID
    WHERE u.ROLE_ID = 2
    GROUP BY u.ID
    ) ,
    q2 AS
    (SELECT NVL(SUM(COUNT(t.id)), 0) AS active_Tasks
    FROM T_GPE_M_PROJECTS p
    INNER JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    INNER JOIN T_GPE_M_TASKS t
    ON t.REQUIREMENT_ID = r.id
    RIGHT JOIN T_GPE_P_TASK_STATUS st
    ON t.TASK_STATUS_ID = st.ID
    WHERE st.id         = 3
    OR st.id            = 12
    GROUP BY st.DESCRIPTION
    ),
    q3 AS
    (SELECT NVL(COUNT(t.id), 0) AS blocked_Tasks
    FROM T_GPE_M_PROJECTS p
    INNER JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    INNER JOIN T_GPE_M_TASKS t
    ON t.REQUIREMENT_ID = r.id
    RIGHT JOIN T_GPE_P_TASK_STATUS st
    ON t.TASK_STATUS_ID = st.ID
    WHERE st.id         = 5
    GROUP BY st.DESCRIPTION
    ),
    q4 AS
    (SELECT NVL(COUNT(t.id), 0) AS delayed_Tasks
    FROM T_GPE_M_PROJECTS p
    INNER JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    INNER JOIN T_GPE_M_TASKS t
    ON t.REQUIREMENT_ID = r.id
    RIGHT JOIN T_GPE_P_TASK_STATUS st
    ON t.TASK_STATUS_ID = st.ID
    WHERE st.id         = 9
    GROUP BY st.DESCRIPTION
    ),
    q5 AS
    (SELECT NVL(SUM(COUNT(t.id)), 0) AS stopped_Tasks
    FROM T_GPE_M_PROJECTS p
    INNER JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    INNER JOIN T_GPE_M_TASKS t
    ON t.REQUIREMENT_ID = r.id
    RIGHT JOIN T_GPE_P_TASK_STATUS st
    ON t.TASK_STATUS_ID = st.ID
    WHERE st.id         = 4
    OR st.id            = 11
    GROUP BY st.DESCRIPTION
    )
  SELECT * FROM q1, q2, q3, q4, q5
    );
--------------------------------------------------------
--  DDL for View V_GPE_MANAGER_DASHBOARD
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW V_GPE_MANAGER_DASHBOARD ("ID", "MANAGER", "PROJECTS", "REQUIREMENTS", "DEVELOPERS", "ACTIVE_TASKS", "BLOCKED_TASKS", "DELAYED_TASKS", "STOPPED_TASKS") AS 
  SELECT rownum id ,
    manager,
    projects,
    requirements,
    developers,
    active_Tasks,
    blocked_Tasks,
    delayed_Tasks,
    stopped_Tasks
  FROM
    (WITH q1 AS
    (SELECT u.ID                  AS manager,
      COUNT(DISTINCT(p.ID))       AS projects,
      COUNT(DISTINCT(r.ID))       AS requirements,
      COUNT(DISTINCT(rd.ID_USER)) AS developers
    FROM T_GPE_M_USERS u
    LEFT JOIN T_GPE_R_PROJECTS_MANAGED pm
    ON u.ID = pm.ID_USER
    LEFT JOIN T_GPE_M_PROJECTS p
    ON pm.ID_PROJECT = p.ID
    LEFT JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    LEFT JOIN T_GPE_R_REQUIREMENTS_DEVELOPED rd
    ON rd.ID_REQUIREMENT = r.ID
    WHERE u.ROLE_ID      = 3
    GROUP BY u.ID
    ) ,
    q2 AS
    (SELECT NVL(SUM(COUNT(t.id)), 0) AS active_Tasks
    FROM T_GPE_M_PROJECTS p
    INNER JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    INNER JOIN T_GPE_M_TASKS t
    ON t.REQUIREMENT_ID = r.id
    RIGHT JOIN T_GPE_P_TASK_STATUS st
    ON t.TASK_STATUS_ID = st.ID
    WHERE st.id         = 3
    OR st.id            = 12
    GROUP BY st.DESCRIPTION
    ),
    q3 AS
    (SELECT NVL(COUNT(t.id), 0) AS blocked_Tasks
    FROM T_GPE_M_PROJECTS p
    INNER JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    INNER JOIN T_GPE_M_TASKS t
    ON t.REQUIREMENT_ID = r.id
    RIGHT JOIN T_GPE_P_TASK_STATUS st
    ON t.TASK_STATUS_ID = st.ID
    WHERE st.id         = 5
    GROUP BY st.DESCRIPTION
    ),
    q4 AS
    (SELECT NVL(COUNT(t.id), 0) AS delayed_Tasks
    FROM T_GPE_M_PROJECTS p
    INNER JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    INNER JOIN T_GPE_M_TASKS t
    ON t.REQUIREMENT_ID = r.id
    RIGHT JOIN T_GPE_P_TASK_STATUS st
    ON t.TASK_STATUS_ID = st.ID
    WHERE st.id         = 9
    GROUP BY st.DESCRIPTION
    ),
    q5 AS
    (SELECT NVL(SUM(COUNT(t.id)), 0) AS stopped_Tasks
    FROM T_GPE_M_PROJECTS p
    INNER JOIN T_GPE_M_REQUIREMENTS r
    ON p.ID = r.PROJECT_ID
    INNER JOIN T_GPE_M_TASKS t
    ON t.REQUIREMENT_ID = r.id
    RIGHT JOIN T_GPE_P_TASK_STATUS st
    ON t.TASK_STATUS_ID = st.ID
    WHERE st.id         = 4
    OR st.id            = 11
    GROUP BY st.DESCRIPTION
    )
  SELECT * FROM q1, q2, q3, q4, q5
    );
--------------------------------------------------------
--  DDL for Index UK_JVQQWOOHHHKFJMN1NL3BUMM4L
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_JVQQWOOHHHKFJMN1NL3BUMM4L ON T_GPE_M_PROJECTS ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_2UJ4V7AQRPADXG9MH0RLD74FP
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_2UJ4V7AQRPADXG9MH0RLD74FP ON T_GPE_M_USERS ("IDENTIFIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_MPG2A2CHBLYN74QPT6A3237TI
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_MPG2A2CHBLYN74QPT6A3237TI ON T_GPE_P_TASK_TYPE ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_CBGUR4V3II5RE574NLBAMPJQI
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_CBGUR4V3II5RE574NLBAMPJQI ON T_GPE_P_DOCUMENT_TYPES ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_SFQC5WKBFRNPFMG9L06SSISHM
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_SFQC5WKBFRNPFMG9L06SSISHM ON T_GPE_M_USERS ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_24LHEVP98QXSMT7LMAH8R9K51
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_24LHEVP98QXSMT7LMAH8R9K51 ON T_GPE_P_REPORT_STATUS ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_90CQGFWT0W4UBJ4K8MKLXW7PF
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_90CQGFWT0W4UBJ4K8MKLXW7PF ON T_GPE_P_PRIORITY ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_BPJFI7IK1OOHGMANEQYDKRUKT
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_BPJFI7IK1OOHGMANEQYDKRUKT ON T_GPE_P_SERVER_TYPE ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_Q4JLEJED9XJCAKAK6P3VW31N7
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_Q4JLEJED9XJCAKAK6P3VW31N7 ON T_GPE_P_PUBLIC_HOLIDAYS ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_II1YYYI5W4E288DBI3GMHWWF5
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_II1YYYI5W4E288DBI3GMHWWF5 ON T_GPE_P_TASK_STATUS ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_QVANQGWA4CCTMBS8I5ULFQIKO
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_QVANQGWA4CCTMBS8I5ULFQIKO ON T_GPE_P_METHODOLOGIES ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_2WNWSN26CO09PYSQUPP9CXP4N
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_2WNWSN26CO09PYSQUPP9CXP4N ON T_GPE_P_REPORT_TYPE ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_BEQTRHSY0LWER7G6NCCSM67DT
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_BEQTRHSY0LWER7G6NCCSM67DT ON T_GPE_M_ROLES ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_3VVIG6UPW1VP5GYUX62GWV6ON
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_3VVIG6UPW1VP5GYUX62GWV6ON ON T_GPE_P_USER_CATEGORY ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  DDL for Index UK_SV0ES9GMY2YQP6IW5NB2EFRPX
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_SV0ES9GMY2YQP6IW5NB2EFRPX ON T_GPE_R_HISTORICAL_PROJECTS ("USER_ID", "PROJECT_ID", "ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE" ;
--------------------------------------------------------
--  Constraints for Table T_GPE_M_INCURREDS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_INCURREDS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_INCURREDS MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_INCURREDS MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_INCURREDS MODIFY ("MINUTES" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_INCURREDS MODIFY ("EXTRA" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_INCURREDS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_INCURREDS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_INCURREDS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_R_REQUIREMENTS_DEVELOPED
--------------------------------------------------------

  ALTER TABLE T_GPE_R_REQUIREMENTS_DEVELOPED MODIFY ("ID_REQUIREMENT" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_REQUIREMENTS_DEVELOPED MODIFY ("ID_USER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_TASK_TYPE
--------------------------------------------------------

  ALTER TABLE T_GPE_P_TASK_TYPE ADD CONSTRAINT "UK_MPG2A2CHBLYN74QPT6A3237TI" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_TASK_TYPE ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_TASK_TYPE MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_R_HISTORICAL_PROJECTS
--------------------------------------------------------

  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS ADD CONSTRAINT "UK_SV0ES9GMY2YQP6IW5NB2EFRPX" UNIQUE ("USER_ID", "PROJECT_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_DOCUMENT_TYPES
--------------------------------------------------------

  ALTER TABLE T_GPE_P_DOCUMENT_TYPES ADD CONSTRAINT "UK_CBGUR4V3II5RE574NLBAMPJQI" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_DOCUMENT_TYPES ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_DOCUMENT_TYPES MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_TASK_STATUS
--------------------------------------------------------

  ALTER TABLE T_GPE_P_TASK_STATUS ADD CONSTRAINT "UK_II1YYYI5W4E288DBI3GMHWWF5" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_TASK_STATUS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_TASK_STATUS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_R_TASKS_DEPENDENCIES
--------------------------------------------------------

  ALTER TABLE T_GPE_R_TASKS_DEPENDENCIES MODIFY ("DEPENDENCY_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_TASKS_DEPENDENCIES MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_GOALS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_GOALS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_GOALS MODIFY ("REQUIREMENT_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_GOALS MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_GOALS MODIFY ("PRIORITY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_GOALS MODIFY ("ACHIEVED" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_GOALS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_GOALS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_GOALS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_TASK_COMMENT
--------------------------------------------------------

  ALTER TABLE T_GPE_M_TASK_COMMENT ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_TASK_COMMENT MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASK_COMMENT MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASK_COMMENT MODIFY ("COMMENTARY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASK_COMMENT MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASK_COMMENT MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASK_COMMENT MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_METHODOLOGIES
--------------------------------------------------------

  ALTER TABLE T_GPE_P_METHODOLOGIES ADD CONSTRAINT "UK_QVANQGWA4CCTMBS8I5ULFQIKO" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_METHODOLOGIES ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_METHODOLOGIES MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_REPORT_STATUS
--------------------------------------------------------

  ALTER TABLE T_GPE_P_REPORT_STATUS ADD CONSTRAINT "UK_24LHEVP98QXSMT7LMAH8R9K51" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_REPORT_STATUS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_REPORT_STATUS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_REPORTS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_REPORTS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_REPORTS MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REPORTS MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REPORTS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REPORTS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REPORTS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_SERVER_TYPE
--------------------------------------------------------

  ALTER TABLE T_GPE_P_SERVER_TYPE ADD CONSTRAINT "UK_BPJFI7IK1OOHGMANEQYDKRUKT" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_SERVER_TYPE ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_SERVER_TYPE MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_USER_CATEGORY
--------------------------------------------------------

  ALTER TABLE T_GPE_P_USER_CATEGORY ADD CONSTRAINT "UK_3VVIG6UPW1VP5GYUX62GWV6ON" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_USER_CATEGORY ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_USER_CATEGORY MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_SERVERS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_SERVERS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_SERVERS MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_SERVERS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_SERVERS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_SERVERS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_DOCUMENTS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_DOCUMENTS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_DOCUMENTS MODIFY ("DOCUMENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_DOCUMENTS MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_DOCUMENTS MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_DOCUMENTS MODIFY ("DEVELOPER_AVAILABILITY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_DOCUMENTS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_DOCUMENTS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_DOCUMENTS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_R_PROJECTS_MANAGED
--------------------------------------------------------

  ALTER TABLE T_GPE_R_PROJECTS_MANAGED MODIFY ("ID_PROJECT" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_PROJECTS_MANAGED MODIFY ("ID_USER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_PUBLIC_HOLIDAYS
--------------------------------------------------------

  ALTER TABLE T_GPE_P_PUBLIC_HOLIDAYS ADD CONSTRAINT "UK_Q4JLEJED9XJCAKAK6P3VW31N7" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_PUBLIC_HOLIDAYS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_PUBLIC_HOLIDAYS MODIFY ("DAY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_P_PUBLIC_HOLIDAYS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_VACATIONS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_VACATIONS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_VACATIONS MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_VACATIONS MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_VACATIONS MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_VACATIONS MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_VACATIONS MODIFY ("APPROVED" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_VACATIONS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_VACATIONS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_VACATIONS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_TODOS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_TODOS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_TODOS MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TODOS MODIFY ("TASK" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TODOS MODIFY ("DONE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TODOS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TODOS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TODOS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_USERS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_USERS ADD CONSTRAINT "UK_2UJ4V7AQRPADXG9MH0RLD74FP" UNIQUE ("IDENTIFIER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_USERS ADD CONSTRAINT "UK_SFQC5WKBFRNPFMG9L06SSISHM" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_USERS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_USERS MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("LOCKED" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("IS_ENABLED" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("IDENTIFIER" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("ATTEMPTS" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_USERS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_TASKS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_TASKS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_TASKS MODIFY ("LAST_EDITION_BY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASKS MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASKS MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASKS MODIFY ("HOURS" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASKS MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASKS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASKS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TASKS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_ROLES
--------------------------------------------------------

  ALTER TABLE T_GPE_M_ROLES ADD CONSTRAINT "UK_BEQTRHSY0LWER7G6NCCSM67DT" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_ROLES ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_ROLES MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_TIMESHEETS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_TIMESHEETS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("WEDNESDAY_HOURS" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("TUESDAY_HOURS" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("THURSDAY_HOURS" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("SUNDAY_HOURS" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("SATURDAY_HOURS" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("MONDAY_HOURS" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("FRIDAY_HOURS" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_TIMESHEETS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_PRIORITY
--------------------------------------------------------

  ALTER TABLE T_GPE_P_PRIORITY ADD CONSTRAINT "UK_90CQGFWT0W4UBJ4K8MKLXW7PF" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_PRIORITY ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_PRIORITY MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_ABSENCES
--------------------------------------------------------

  ALTER TABLE T_GPE_M_ABSENCES ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_ABSENCES MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_ABSENCES MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_ABSENCES MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_ABSENCES MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_ABSENCES MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_ABSENCES MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_REQUIREMENTS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_REQUIREMENTS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("LAST_EDITION_BY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("ARCHIVED" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_REQUIREMENTS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_M_PROJECTS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_PROJECTS ADD CONSTRAINT "UK_JVQQWOOHHHKFJMN1NL3BUMM4L" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_PROJECTS ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("METHODOLOGY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("PROJECT_LEADER" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("LAST_EDITION_BY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("ARCHIVED" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE T_GPE_M_PROJECTS MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_R_TASKS_ASSIGNED
--------------------------------------------------------

  ALTER TABLE T_GPE_R_TASKS_ASSIGNED MODIFY ("ID_TASK" NOT NULL ENABLE);
  ALTER TABLE T_GPE_R_TASKS_ASSIGNED MODIFY ("ID_USER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GPE_P_REPORT_TYPE
--------------------------------------------------------

  ALTER TABLE T_GPE_P_REPORT_TYPE ADD CONSTRAINT "UK_2WNWSN26CO09PYSQUPP9CXP4N" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_REPORT_TYPE ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GPE"  ENABLE;
  ALTER TABLE T_GPE_P_REPORT_TYPE MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_ABSENCES
--------------------------------------------------------

  ALTER TABLE T_GPE_M_ABSENCES ADD CONSTRAINT "FK_LBNQ7XGPJIRKO8L6I4WNSE7PB" FOREIGN KEY ("USER_ID")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_DOCUMENTS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_DOCUMENTS ADD CONSTRAINT "FK_5Q53WX08G48RJ8IDBYYXGIV32" FOREIGN KEY ("DOCUMENT_TYPE_ID")
	  REFERENCES T_GPE_P_DOCUMENT_TYPES ("ID") ENABLE;
  ALTER TABLE T_GPE_M_DOCUMENTS ADD CONSTRAINT "FK_LVTFBQICERHB9YCQD0LQGSI22" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES T_GPE_M_PROJECTS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_DOCUMENTS ADD CONSTRAINT "FK_SOGXU90NU8IEC27HSCJI1TLOQ" FOREIGN KEY ("REQUIREMENT_ID")
	  REFERENCES T_GPE_M_REQUIREMENTS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_GOALS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_GOALS ADD CONSTRAINT "FK_IJ4BIHY6CO0JHCOBLUTCT6FBM" FOREIGN KEY ("REQUIREMENT_ID")
	  REFERENCES T_GPE_M_REQUIREMENTS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_INCURREDS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_INCURREDS ADD CONSTRAINT "FK_56COJNS27MA9RPGHANMN7FRTV" FOREIGN KEY ("TASK_ID")
	  REFERENCES T_GPE_M_TASKS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_INCURREDS ADD CONSTRAINT "FK_NJNWEVLPBJIMVE09B8C8B729E" FOREIGN KEY ("USER_ID")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_PROJECTS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_PROJECTS ADD CONSTRAINT "FK_6UQTNYOQ0JF72R1DFVWWYJ619" FOREIGN KEY ("PRODUCT_OWNER")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_PROJECTS ADD CONSTRAINT "FK_8OO7W5KLNYRF09KQ7TCTACLCY" FOREIGN KEY ("METHODOLOGY")
	  REFERENCES T_GPE_P_METHODOLOGIES ("ID") ENABLE;
  ALTER TABLE T_GPE_M_PROJECTS ADD CONSTRAINT "FK_F57DVI3AVS24Y1GMQ7XY5HF5I" FOREIGN KEY ("SCRUM_MASTER")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_PROJECTS ADD CONSTRAINT "FK_GFMCJPP46PK8Q1NV0AEOR6DMG" FOREIGN KEY ("PROJECT_LEADER")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_REPORTS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_REPORTS ADD CONSTRAINT "FK_EID0SQ6WIY37TJN2H4R0K1DD5" FOREIGN KEY ("REPORT_STATUS")
	  REFERENCES T_GPE_P_REPORT_STATUS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_REPORTS ADD CONSTRAINT "FK_LYF9MVHJPVQTUJ9YFBT7A6DLF" FOREIGN KEY ("REPORT_TYPE")
	  REFERENCES T_GPE_P_REPORT_TYPE ("ID") ENABLE;
  ALTER TABLE T_GPE_M_REPORTS ADD CONSTRAINT "FK_T061DJLNL2N3UWM3BTMUK49Y5" FOREIGN KEY ("USER_ID")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_REQUIREMENTS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_REQUIREMENTS ADD CONSTRAINT "FK_7I9P8LQWQ67CKJG2Y6AWF7DGO" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES T_GPE_M_PROJECTS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_REQUIREMENTS ADD CONSTRAINT "FK_AVWPB9BMVCWQQMMKFGRS8LEJQ" FOREIGN KEY ("CREATED_BY")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_REQUIREMENTS ADD CONSTRAINT "FK_I9F7FDGDAPVOQ9HENAGD735FD" FOREIGN KEY ("LAST_EDITION_BY")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_SERVERS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_SERVERS ADD CONSTRAINT "FK_1W9VMF8PGH316RHSKPGX0USBP" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES T_GPE_M_PROJECTS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_SERVERS ADD CONSTRAINT "FK_KS4QXC3JBGK4696KOC7U4PCDG" FOREIGN KEY ("SERVER_TYPE")
	  REFERENCES T_GPE_P_SERVER_TYPE ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_TASK_COMMENT
--------------------------------------------------------

  ALTER TABLE T_GPE_M_TASK_COMMENT ADD CONSTRAINT "FK_H2R1LYJCWXK03OK19BBCN7LN5" FOREIGN KEY ("USER_ID")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_TASK_COMMENT ADD CONSTRAINT "FK_LVRI66L6SJ7XC7DDK5UFRTG2X" FOREIGN KEY ("TASK_ID")
	  REFERENCES T_GPE_M_TASKS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_TASKS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_TASKS ADD CONSTRAINT "FK_18M8HSNSIOBM7NCTI3DRP13UU" FOREIGN KEY ("PARENT_ID")
	  REFERENCES T_GPE_M_TASKS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_TASKS ADD CONSTRAINT "FK_4WMY2EBHO6OE6JXKVFMBH2T8E" FOREIGN KEY ("TASK_STATUS_ID")
	  REFERENCES T_GPE_P_TASK_STATUS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_TASKS ADD CONSTRAINT "FK_7BVCR10CDIEYH56C30XLYL0GK" FOREIGN KEY ("REQUIREMENT_ID")
	  REFERENCES T_GPE_M_REQUIREMENTS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_TASKS ADD CONSTRAINT "FK_7VGYET2C62LAT735CQUCQ1OCQ" FOREIGN KEY ("TASK_TYPE_ID")
	  REFERENCES T_GPE_P_TASK_TYPE ("ID") ENABLE;
  ALTER TABLE T_GPE_M_TASKS ADD CONSTRAINT "FK_CAHBV4FI3WLMNE949BYXRDL63" FOREIGN KEY ("TASK_PRIORITY_ID")
	  REFERENCES T_GPE_P_PRIORITY ("ID") ENABLE;
  ALTER TABLE T_GPE_M_TASKS ADD CONSTRAINT "FK_HF2194AOFIGKMY60YL4WFG0YS" FOREIGN KEY ("CREATED_BY")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
  ALTER TABLE T_GPE_M_TASKS ADD CONSTRAINT "FK_OXEKGO2DCWE4KN5SL5OH7DSA0" FOREIGN KEY ("LAST_EDITION_BY")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_TIMESHEETS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_TIMESHEETS ADD CONSTRAINT "FK_J4Y23NSUQCKNVKYT6FUTRTAKN" FOREIGN KEY ("USER_ID")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_TODOS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_TODOS ADD CONSTRAINT "FK_54DVM5NFQTEK5CIWDRH25NO64" FOREIGN KEY ("USER_ID")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_USERS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_USERS ADD CONSTRAINT "FK_PSQ08LH6GGUXKTRB7HD39P8HF" FOREIGN KEY ("ROLE_ID")
	  REFERENCES T_GPE_M_ROLES ("ID") ENABLE;
  ALTER TABLE T_GPE_M_USERS ADD CONSTRAINT "FK_PUTFGCJ2EXWJL8TY9LFRAJ2UV" FOREIGN KEY ("USER_POSITION")
	  REFERENCES T_GPE_P_USER_CATEGORY ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_M_VACATIONS
--------------------------------------------------------

  ALTER TABLE T_GPE_M_VACATIONS ADD CONSTRAINT "FK_9M3YET76J7UTWGVM32C3PCN2" FOREIGN KEY ("USER_ID")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_R_HISTORICAL_PROJECTS
--------------------------------------------------------

  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS ADD CONSTRAINT "FK_1987CFN4I8OX63XDOO2W9NV8B" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES T_GPE_M_PROJECTS ("ID") ENABLE;
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS ADD CONSTRAINT "FK_4CV0VF3KKA0LBTR5UTER10UEU" FOREIGN KEY ("USER_ID")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS ADD CONSTRAINT "FK_LS66QUR85BPB0SU8KGRQYTRJ0" FOREIGN KEY ("ROLE_ID")
	  REFERENCES T_GPE_M_ROLES ("ID") ENABLE;
  ALTER TABLE T_GPE_R_HISTORICAL_PROJECTS ADD CONSTRAINT "FK_SHN01AN83JA7TOTWUH85ISFPP" FOREIGN KEY ("REQUIREMENT_ID")
	  REFERENCES T_GPE_M_REQUIREMENTS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_R_PROJECTS_MANAGED
--------------------------------------------------------

  ALTER TABLE T_GPE_R_PROJECTS_MANAGED ADD CONSTRAINT "FK_7CLEQJIUNQMJBP1R91U8KAQQP" FOREIGN KEY ("ID_USER")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
  ALTER TABLE T_GPE_R_PROJECTS_MANAGED ADD CONSTRAINT "FK_OTCB71HB0QMJAKC7T5POSRRGF" FOREIGN KEY ("ID_PROJECT")
	  REFERENCES T_GPE_M_PROJECTS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_R_REQUIREMENTS_DEVELOPED
--------------------------------------------------------

  ALTER TABLE T_GPE_R_REQUIREMENTS_DEVELOPED ADD CONSTRAINT "FK_E4SLT8VRDM0Q7MAXBBQWEWAH3" FOREIGN KEY ("ID_REQUIREMENT")
	  REFERENCES T_GPE_M_REQUIREMENTS ("ID") ENABLE;
  ALTER TABLE T_GPE_R_REQUIREMENTS_DEVELOPED ADD CONSTRAINT "FK_N4BA0FNJR5I0JD4M6I62GS5SD" FOREIGN KEY ("ID_USER")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_R_TASKS_ASSIGNED
--------------------------------------------------------

  ALTER TABLE T_GPE_R_TASKS_ASSIGNED ADD CONSTRAINT "FK_ITDQGJJ5FIISWRLYNISSOVRYJ" FOREIGN KEY ("ID_TASK")
	  REFERENCES T_GPE_M_TASKS ("ID") ENABLE;
  ALTER TABLE T_GPE_R_TASKS_ASSIGNED ADD CONSTRAINT "FK_O8LFVN2RAQ0VDIIJEE0XKEXE7" FOREIGN KEY ("ID_USER")
	  REFERENCES T_GPE_M_USERS ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_GPE_R_TASKS_DEPENDENCIES
--------------------------------------------------------

  ALTER TABLE T_GPE_R_TASKS_DEPENDENCIES ADD CONSTRAINT "FK_DKVBIP19MIKTY98N0IRI1F1Y2" FOREIGN KEY ("DEPENDENCY_ID")
	  REFERENCES T_GPE_M_TASKS ("ID") ENABLE;
  ALTER TABLE T_GPE_R_TASKS_DEPENDENCIES ADD CONSTRAINT "FK_H5RWOLXU2MAHVBOJA8DCLMVJO" FOREIGN KEY ("TASK_ID")
	  REFERENCES T_GPE_M_TASKS ("ID") ENABLE;
